mod color;
mod mat4;
mod material;
mod ray;
mod rect;
mod scene;
mod sphere;
mod vec3;

pub type Vec3 = vec3::Vec3;
pub type Mat4 = mat4::Mat4;
pub type Ray = ray::Ray;
pub type Shape = scene::Shape;
pub type Sphere = sphere::Sphere;
pub type Rect = rect::Rect;
pub type RayHit<'a> = scene::RayHit<'a>;
pub type Scene = scene::Scene;
pub type Material = material::Material;
pub type Entity = scene::Entity;
pub type Color = color::Color;
